### PR TITLE
Marvelous pull. Enjoy it!!!

### PR DESCRIPTION
**Pull request by marianoalvarosaiz**

### CODE REVIEW

**Comment by marianoalvarosaiz** [comment]
If you want to test the amazing outputs of the script:

```import com.liferay.portal.kernel.util.StringUtil;

out.println(_getSafeString("a ñ", "UTF-8", 3));

private String _getSafeString(String value, String charset, int maxLength)
    throws Exception {

    byte[] valueBytes = value.getBytes("UTF-8");

    if (valueBytes.length <= maxLength) {
        return value;
    }

    byte[] convertedValue = new byte[maxLength];

    System.arraycopy(valueBytes, 0, convertedValue, 0, maxLength);

    String returnValue = new String(convertedValue, charset);

    return StringUtil.shorten(returnValue, returnValue.length() - 1);
}

**Comment by marianoalvarosaiz** [comment]
garbage

**Comment by marianoalvarosaiz** [comment]
ci:reopen

**Comment by marianoalvarosaiz** [comment]
NoSuchGarbageException

**Comment by crodriguezy** [comment]
LGTM BTW

**Pull request closed without merging**
