### PR TITLE
LPS-98828

### PR DESCRIPTION
**Pull request by fortunatomaldonado**
https://issues.liferay.com/browse/LPS-98828

Hello @crodriguezy,

I was able to find that both inputs need to have validators in order to  maintain the asterisks and provide an error message for the repeatable D&M field.

I needed to adjust the errorMessage for the first input to a blank space or else there would be two error messages appearing for the first D&M field.
When the field is repeated, the field does not seem to carry over the first validator and so it does not produce an error message. This is why I re-added the validator to the second input.
Please let me know if there are any questions or comments about this.
Thank you.

### CODE REVIEW

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:relevant

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by fortunatomaldonado** [comment]
ci:test:sf

**Comment by ricardocousolr** [comment]
Hi @fortunatomaldonado,

Cristina is out-of-office so I'm taking over for this issue. 

On the issue itself, I've noticed that the same faulty behavior happens for other ddm fields, besides Documents&Media: Link to Page (`link-to-page.ftl`), Web Content Article (`journal-article.ftl`) and Image (`image.ftl`). So we should make sure that for all this fields the solution works.

On the solution, I haven't been able to obtain the expected behavior with it: I don't get any error if I leave the original D&M field empty and I don't get any message or visual red input for a repeated D&M field. Could you confirm that it is indeed working correctly for you, as this might be a problem with my environment?

I was also hoping that we wouldn't need to resort to using an empty errorMessage. It feels like we might be missing the actual source of the issue and we're going around it. What do you think?

Regards.

**Comment by fortunatomaldonado** [comment]
Hello @ricardocousolr,

Okay I will update LPS-98828 to include those fields as well.

For some reason you have to stop and restart Liferay to see the changes after you deploy it. This was the only way I found that works. I thought it might have been my environment but it could be the case for everyone.

Yes I agree there seems to be an underlying issue that should be investigated further. The above solution can be used as a workaround for now if a customer is pushing for a solution.

**Comment by fortunatomaldonado** [comment]
Hello @ricardocousolr,

Before the changes of https://issues.liferay.com/browse/LPS-94945, the fields worked as intended despite not having an asterisks when the field was required. It worked since the hidden input would take care of the validation.
Once we removed the validation form the hidden input and gave validation to visible input, the asterisk and error message only worked for the initial field but not for any of the repeatable duplicates. The repeatables were using the hidden field to validate the field and does not take into account the visible input with validation. We can start by looking into why the repeatables are ignoring the validation from the visible field. 
Any help and insight would be appreciate to come to a quicker solution.
Thank you.

**Comment by ricardocousolr** [comment]
Thank you for your answer, @fortunatomaldonado. 

After restart the changes apply as you mentioned. I'll provide this workaround solution to the customer since I believe is good enough for the moment. 

I'll try and have a look at why repeatables aren't behaving like other fields and get back to you with any results I can get.

**Comment by fortunatomaldonado** [comment]
@ricardocousolr, sounds good.

I'll be closing this PR since it will not be used for the final solution.

**Pull request closed without merging**
